name: Recipe Helper CI

on:
  push:
    branch: [master]
  pull_request: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 10s --health-retries 5

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Run a Hello, World
        run: echo Hello, world!

      - name: User Node JS version 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install local dependencies
        run: npm install

      - name: Run Server win Dev
        run: npm run server-dev
